### ISSUE TITLE
Why new?

### ISSUE THREAD

**Issue by Megunolink** [felias-fogg/SlowSoftWire#1]
Hello,

I was wondering why you used `new` when creating the `SlowSoftI2CMaster` on line 13 of SlowSoftWire?

If you make si2c a `SlowSoftI2CMaster` variable rather than a pointer to one, then `new` isn't needed. Instead, I think your SlowSoftWire constructor becomes:
```
SlowSoftWire::SlowSoftWire(uint8_t sda, uint8_t scl) 
  : si2c(sda, scl)
{
}
```

This would be super helpful on the ATTiny88 we'd like to use the library on. But using `new` causes it to try and setup a heap, which I think has a lot of overhead and we only have 8k for the whole program!

Is that something you'd consider changing? I can make the changes and send you a pull request if that's helpful. 

Thanks for making the library!
paul

**Comment by felias-fogg** [comment]
Hi Paul,

yes, go ahead and change it and I re-integrate it. By the way: Why don’t you use SoftWire and SoftI2CMaster? The memory footprint is smaller and it is faster!

Best,
Bernhard

**Comment by Megunolink** [comment]
Thanks Bernhard. I'll let you know when I've done the changes. 

Unfortunately we can't use SoftI2CMaster; it has a GPL license and we need to use it in a closed source application. Fortunately we can do that with your use of LGPL. Of course, happy to contribute our changes back to your library!

Have a great day
Paul.

**Comment by felias-fogg** [comment]
I changed the vars to be static.
